version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_loberia
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lucaleo100
      POSTGRES_DB: LoberiaTurismoPrueba
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_cards.sql:/docker-entrypoint-initdb.d/init_cards.sql
    restart: always

volumes:
  pgdata:

